"use client";

import React, { useState } from "react";
import jsPDF from "jspdf";
import { formatRupiah, formatTerbilang } from "@/lib/format";
import { generateKwitansiNo } from "@/app/actions";
import { useRouter } from "next/navigation";

export default function KuitansiClient({ transactions, companyProfile }: any) {
  const [isGenerating, setIsGenerating] = useState<string | null>(null);
  const router = useRouter();

  const handlePrint = async (tx: any) => {
    setIsGenerating(tx.id);
    try {
      let kwitansiNo = tx.kwitansiNo;
      
      // 1. Generate No Kuitansi if not exists
      if (!kwitansiNo) {
        const result = await generateKwitansiNo(tx.id);
        if (result.success) {
          kwitansiNo = result.kwitansiNo;
          router.refresh();
        } else {
          alert(result.error);
          return;
        }
      }

      // 2. Generate PDF
      const doc = new jsPDF({
        orientation: "landscape",
        unit: "mm",
        format: [210, 148], // A5 Landscape
      });

      // Styling constants
      const primaryColor = "#EA6C00";
      const margin = 15;
      const width = doc.internal.pageSize.getWidth();

      // Header - Box
      doc.setDrawColor(200);
      doc.setLineWidth(0.5);
      doc.rect(margin, margin, width - margin * 2, 25);

      // Company Info
      doc.setFont("helvetica", "bold");
      doc.setFontSize(14);
      doc.text(companyProfile?.name || "SIAGMS", margin + 5, margin + 8);
      
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8);
      doc.setTextColor(100);
      doc.text(companyProfile?.address || "-", margin + 5, margin + 13);
      doc.text(`Telp: ${companyProfile?.phone || "-"}`, margin + 5, margin + 18);

      // Title
      doc.setFontSize(18);
      doc.setTextColor(0);
      doc.setFont("helvetica", "bold");
      doc.text("K U I T A N S I", width / 2, margin + 45, { align: "center" });

      // No & Date
      doc.setFontSize(10);
      doc.text(`No. Kuitansi : ${kwitansiNo}`, margin + 5, margin + 55);
      doc.text(`Tanggal      : ${new Date(tx.date).toLocaleDateString("id-ID", { day: '2-digit', month: 'long', year: 'numeric' })}`, margin + 5, margin + 60);

      // Content Box
      doc.setDrawColor(230);
      doc.line(margin, margin + 65, width - margin, margin + 65);

      // Content rows
      const startY = margin + 75;
      const rowH = 8;
      
      doc.setFont("helvetica", "normal");
      doc.text("Diterima dari", margin + 5, startY);
      doc.text(":  " + (tx.customer?.name || "-"), margin + 40, startY);

      doc.text("Jumlah", margin + 5, startY + rowH);
      doc.setFont("helvetica", "bold");
      doc.text(":  " + formatRupiah(tx.amount), margin + 40, startY + rowH);

      doc.setFont("helvetica", "italic");
      doc.setFontSize(9);
      doc.text("( " + formatTerbilang(tx.amount) + " )", margin + 40, startY + rowH * 2);

      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      doc.text("Untuk", margin + 5, startY + rowH * 3.5);
      doc.text(":  " + (tx.description || "-"), margin + 40, startY + rowH * 3.5);

      doc.text("Proyek", margin + 5, startY + rowH * 4.5);
      doc.text(":  " + (tx.project?.name || "-"), margin + 40, startY + rowH * 4.5);

      doc.text("Unit", margin + 5, startY + rowH * 5.5);
      doc.text(":  " + (tx.unit ? `${tx.unit.unitCode} / Blok ${tx.unit.blockName}${tx.unit.unitNumber}` : "-"), margin + 40, startY + rowH * 5.5);

      // Signature area
      const sigX = width - margin - 40;
      const sigY = startY + rowH * 5;
      doc.setFont("helvetica", "normal");
      doc.text("Hormat kami,", sigX, sigY);
      doc.line(sigX - 5, sigY + 20, sigX + 25, sigY + 20);
      doc.text("Kasir/Admin", sigX, sigY + 25);

      // Footer - Website/Watermark etc if needed
      doc.setFontSize(7);
      doc.setTextColor(200);
      doc.text("Generated by SIAGMS", width - margin - 30, doc.internal.pageSize.getHeight() - 5);

      // Save
      doc.save(`Kuitansi_${kwitansiNo}.pdf`);

    } catch (err: any) {
      alert("Gagal mencetak: " + err.message);
    } finally {
      setIsGenerating(null);
    }
  };

  return (
    <div suppressHydrationWarning className="border-2 shadow-xl border-gray-200 dark:border-gray-800 rounded-2xl bg-gray-100 dark:bg-[#0f172a] text-gray-600 dark:text-gray-300 pt-4 md:p-5 md:pt-5 min-h-screen">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-8 px-4 md:px-0">
        <div>
          <h1 className="text-3xl font-bold text-gray-900 dark:text-gray-100 tracking-tight">
            Kuitansi
          </h1>
          <p className="text-sm text-gray-400 dark:text-gray-500 mt-3">
            Ringkasan transaksi penerimaan yang siap untuk penerbitan kuitansi resmi.
          </p>
        </div>
      </div>

      <div className="bg-white dark:bg-slate-800 rounded-[14px] border-[0.5px] border-[#E5E7EB] dark:border-slate-700 shadow-sm overflow-hidden mx-4 md:mx-0">
        <div className="overflow-x-auto">
          <table className="w-full min-w-[1000px]">
            <thead className="bg-[#F9FAFB] dark:bg-slate-800/80 border-b border-gray-100 dark:border-slate-700">
              <tr>
                <th className="px-6 py-4 text-left text-[10px] font-semibold text-gray-400 uppercase tracking-[0.15em]">Tanggal</th>
                <th className="px-6 py-4 text-left text-[10px] font-semibold text-gray-400 uppercase tracking-[0.15em]">No. Kuitansi</th>
                <th className="px-6 py-4 text-left text-[10px] font-semibold text-gray-400 uppercase tracking-[0.15em]">Pelanggan</th>
                <th className="px-6 py-4 text-left text-[10px] font-semibold text-gray-400 uppercase tracking-[0.15em]">Unit</th>
                <th className="px-6 py-4 text-left text-[10px] font-semibold text-gray-400 uppercase tracking-[0.15em]">Kategori</th>
                <th className="px-6 py-4 text-right text-[10px] font-semibold text-gray-400 uppercase tracking-[0.15em]">Jumlah</th>
                <th className="px-6 py-4 text-center text-[10px] font-semibold text-gray-400 uppercase tracking-[0.15em]">Status</th>
                <th className="px-6 py-4 text-right text-[10px] font-semibold text-gray-400 uppercase tracking-[0.15em]">Aksi</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-50 dark:divide-slate-700/50">
              {transactions.map((transaction: any) => (
                <tr key={transaction.id} className="hover:bg-[#FFF0E6]/30 dark:hover:bg-slate-700/40 transition-all duration-150">
                  <td suppressHydrationWarning className="px-6 py-4 text-sm text-slate-900 dark:text-gray-100">
                    {new Date(transaction.date).toLocaleDateString("id-ID")}
                  </td>
                  <td className="px-6 py-4 text-sm font-semibold text-slate-900 dark:text-gray-100">
                    {transaction.kwitansiNo || <span className="text-gray-300 font-normal italic">Belum ada</span>}
                  </td>
                  <td className="px-6 py-4 text-sm text-gray-500 dark:text-gray-400">
                    {transaction.customer?.name || "-"}
                  </td>
                  <td className="px-6 py-4 text-sm text-gray-500 dark:text-gray-400">
                    {transaction.unit ? `${transaction.unit.unitCode}` : "-"}
                  </td>
                  <td className="px-6 py-4 text-sm text-gray-400 italic">
                    {transaction.category.replace('_', ' ')}
                  </td>
                  <td className="px-6 py-4 text-sm text-right font-bold text-[#EA6C00]">
                    {formatRupiah(transaction.amount)}
                  </td>
                  <td className="px-6 py-4 text-center">
                    {transaction.kwitansiNo ? (
                      <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-[10px] font-black uppercase tracking-wider bg-emerald-100 text-emerald-800 dark:bg-emerald-900/30 dark:text-emerald-400 border border-emerald-200 dark:border-emerald-800">
                        Sudah Dicetak
                      </span>
                    ) : (
                      <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-[10px] font-black uppercase tracking-wider bg-gray-100 text-gray-600 dark:bg-slate-700 dark:text-gray-400">
                        Belum Dicetak
                      </span>
                    )}
                  </td>
                  <td className="px-6 py-4 text-right">
                    <button
                      onClick={() => handlePrint(transaction)}
                      disabled={isGenerating === transaction.id}
                      className="px-4 py-2 bg-[#EA6C00] hover:bg-[#d56200] disabled:opacity-50 text-white text-xs font-bold rounded-[8px] transition-all active:scale-95 flex items-center gap-2 float-right shadow-lg shadow-orange-500/10"
                    >
                      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor" className="w-3.5 h-3.5">
                        <path strokeLinecap="round" strokeLinejoin="round" d="M6.72 13.844l-.452 2.258A1.745 1.745 0 007.973 18.12h8.054a1.745 1.745 0 001.705-2.018l-.452-2.258m-10.287 0a2.392 2.392 0 010-3.142l.333-.333a2.391 2.391 0 013.141 0l.334.333a2.391 2.391 0 003.142 0l.333-.333a2.391 2.391 0 013.142 0l.333.333a2.391 2.391 0 010 3.142m-10.287 0l8.054-.001" />
                      </svg>
                      {isGenerating === transaction.id ? "Memproses..." : "Cetak"}
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {transactions.length === 0 && (
          <div className="p-12 text-center">
            <p className="text-gray-500 dark:text-gray-400 font-medium">Belum ada transaksi yang siap dijadikan kuitansi.</p>
          </div>
        )}
      </div>
    </div>
  );
}
